### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by notow666** [liuzhihang/doc-view#2]
线上搜不到，线下无法安，什么玩意

**Comment by liuzhihang** [comment]
@notow666 

已经提交插件仓库了，但是还没有通过审核。

官方因为不兼容 203 版本 给驳回了。现在已经去掉了。仅仅支持 201 202 版本。 也就是 IDEA 2020.1  2020.2 版本。

如果用不了，我只能说抱歉了哈。

**Comment by notow666** [comment]
挺好的东西，赶紧升级啊，一键导出，导出格式选择，自定义模板、、、、

**Comment by liuzhihang** [comment]
@notow666  你现在试一下可以用了么。 官方审核还没有通过。 203 版本 API 又改了。

这个我也想，可以提建议，我也在研究你说的这些，包括支持 dubbo ，导出 html，批量导出，单个导出。不过毕竟个人经历有限。

希望可以理解。

使用过程中有 bug，意见和建议都可以提出来。

🌹

**Comment by liuzhihang** [comment]
@notow666 

![image](https://user-images.githubusercontent.com/26057042/98100360-b6437280-1ecb-11eb-8f83-dc865c2d9314.png)


已经可以搜到了。
