### ISSUE TITLE
当接口定义返回的数据类型是集合时，集合的标识丢失

### ISSUE THREAD

**Issue by zh-d-d** [liuzhihang/doc-view#24]
**Bug 描述**
当接口定义返回的数据类型是集合时，集合的标识丢失。
具体表现在两个地方，其中一个地方如下所示：

**Version**
 - Doc View: [e.g. v1.1.7]
 - IDEA [e.g. 2021.1.3]

**Bug 详情**
接口定义如下：

```
    /**
     * 人员列表
     *
     * @return
     */
    @GetMapping("/api/person/list")
    public List<Person> personList() {
        return null;
    }
```

实体类详情如下：

```
@Data
public class Person {

    /**
     * 姓名
     */
    private String name;

    /**
     * 年龄
     */
    private Integer age;
}

```

上传到yapi上的结果如下：

![image](https://user-images.githubusercontent.com/11935073/128617907-b881e78a-8c6a-4577-b064-6168e227ada4.png)

期望结果如下

![image](https://user-images.githubusercontent.com/11935073/128617914-cd0c1251-6716-4e01-8c7b-6e4b008a08b9.png)

**Comment by liuzhihang** [comment]
https://github.com/liuzhihang/doc-view/releases/tag/v1.1.8
