### ISSUE TITLE
idea 2021.2右键没反应

### ISSUE THREAD

**Issue by RuoBingCoder** [liuzhihang/doc-view#26]
**idea 2021.2右键没反应**
 在idea中controller方法右键没有弹窗，没反应！
也没有报错信息！

**Version**
 - Doc View: [e.g. v1.0.0]
 - IDEA [e.g. 2021.2]

**Comment by liuzhihang** [comment]
我这边也是 IDEA 2021.2 版本 没有任何问题。

<img width="450" alt="image" src="https://user-images.githubusercontent.com/26057042/129508041-0620e71b-7ab1-4808-b58d-f60cb7744274.png">

当前参数是什么？
