### ISSUE TITLE
无法识别注释中@param的内容

### ISSUE THREAD

**Issue by binzhou75** [liuzhihang/doc-view#27]
**希望增加什么功能**
 在生成请求参数时，希望能从方法注释中的 @param 行中提取参数的描述信息。

**该功能的使用场景**
生成请求参数列表中具有描述信息

**建议或实现方式**

**Comment by liuzhihang** [comment]
是 get 请求的 param 参数么

**Comment by binzhou75** [comment]
/**
     * 获取工作组所属观测点信息，非树状结构，便于表格展示
     * @param batchid - 批次ID
     * @param groupid - 工作组ID
     * @param currentUser - 当前用户
     * @return - 表格结构的观测点信息
     */
    @RequestMapping(value = "/flatindicators",method = RequestMethod.GET)
    public NicResult GetFlatIndicators(@RequestParam String batchid,
                                       @RequestParam String groupid,
                                       @CurrentUser PersonVo currentUser){
        return igroupService.GetFlatIndicators(batchid,groupid,currentUser);
    }
以上面的代码为例，接口方法中的参数在注释中有描述性的信息，但是生成的md文档中没有这些信息

**Comment by liuzhihang** [comment]
已经修复

**Comment by liuzhihang** [comment]
﻿
﻿
﻿
﻿
﻿收到。

发自我的iPhone
