### ISSUE TITLE
get请求无法正确读取请求参数

### ISSUE THREAD

**Issue by chen1044316902** [liuzhihang/doc-view#35]
**Bug 描述**
get请求无法正确读取请求参数,导致设置的必填参数无法正确上传yapi

接口定义
![image](https://user-images.githubusercontent.com/31918675/140851336-1fec3ba8-9354-4206-a31d-64c091d83dde.png)

Doc editor
![image](https://user-images.githubusercontent.com/31918675/140851423-bb5b3853-a300-4973-9365-8b1f3a3513a3.png)

upload to yapi
![image](https://user-images.githubusercontent.com/31918675/140851530-14f83c33-be6f-476f-bdf5-79bd3373a786.png)

**Version**
 - Doc View: [e.g. v1.2.0]
 - IDEA [e.g. 2021.1]

**Bug 详情**
异常日志、可能导致的原因、参数信息等

**Comment by liuzhihang** [comment]
这里解析的是 @RequestParam 下一版会进行优化
![image](https://user-images.githubusercontent.com/26057042/142372484-934c2b92-b748-454a-8a2e-f398ed4544bc.png)
