### ISSUE TITLE
idea 2021.3安装1.2.1失败

### ISSUE THREAD

**Issue by duallen** [liuzhihang/doc-view#36]
**Bug 描述**
简要描述 Bug 信息

**Version**
 - Doc View: v1.2.1
 - IDEA : 2021.3

**Bug 详情**
安装失败
<img width="956" alt="企业微信截图_78be253e-0823-4c8c-af90-dd79007b3d3f" src="https://user-images.githubusercontent.com/34022801/144555060-5a469962-e118-46d7-b493-8681701f7315.png">

**Comment by liuzhihang** [comment]
你直接在搜索框搜索 Doc View 试一下

**Comment by duallen** [comment]
@liuzhihang 在market里找不到才从硬盘安装的呢
<img width="522" alt="企业微信截图_5a3e74dc-f4ae-4de7-be9e-b79cc4109b4c" src="https://user-images.githubusercontent.com/34022801/144557041-a1130614-1d71-4c5a-9e2a-492a5f99dcae.png">

**Comment by liuzhihang** [comment]
确保下 IDEA 版本，最好是在 2020.3 以后的版本

![image](https://user-images.githubusercontent.com/26057042/144557181-d0811c65-56ec-43a2-b224-11d354be86c7.png)

**Comment by duallen** [comment]
@liuzhihang 确实是我版本的问题，已解决，感谢

**Comment by liuzhihang** [comment]
感谢支持，使用过程有什么意见建议，欢迎反馈
