### ISSUE TITLE
参数列表为空

### ISSUE THREAD

**Issue by HwwwwwLemon** [liuzhihang/doc-view#37]
**Bug 描述**
简要描述 Bug 信息

无法显示参数信息，任何类型请求都无法获得controller的参数列表。
倒是某些返回值可以成功匹配。

**Version**
 - Doc View: v1.2.1
 - IDEA  2021.3

**Bug 详情**
异常日志、可能导致的原因、参数信息等

未知

**Comment by liuzhihang** [comment]
具体能截图或者发一下方法内容么

**Comment by HwwwwwLemon** [comment]
![d35a16e95144066948b3f3684b8814e2a6f95e458a1f7cb52c98d3f46af4d4e7QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQwODg2NTI0NV9DOUI0MjRENC04RjdBLTQyM2QtQUZCQS03MjQ0RDk4QThEMkEucG5n](https://user-images.githubusercontent.com/47653238/145839588-0f9477af-a52c-42b1-962a-3eb4144bfa01.png)
![92e6b656f7a5312da10c651053dba7b55e3d1669efb65a44a522f44c65a5da56QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQwODkwMDI2NF9BNDM3MzM1Qy1DN0JGLTQxNTEtQjc0Mi0wNTJCQzY5QUZBQjQucG5n](https://user-images.githubusercontent.com/47653238/145839601-6ad0ec60-6ad6-4097-8c3d-e75331e261f4.png)

![fe42cec8c663a63acc5403cabb0e4c47ce6f3935c3a7ef7498d425a96715df72QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQwODY2NzY2NF8xNkE0Nzc0Qi1ERkQ1LTQ4Y2UtQjM4Ny0wMUMyMTI5QUZBNzEucG5n](https://user-images.githubusercontent.com/47653238/145839614-7063359b-280c-4317-9a55-ce39d7a930a5.png)


获取参数好像出错了

**Comment by HwwwwwLemon** [comment]
> ![d35a16e95144066948b3f3684b8814e2a6f95e458a1f7cb52c98d3f46af4d4e7QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQwODg2NTI0NV9DOUI0MjRENC04RjdBLTQyM2QtQUZCQS03MjQ0RDk4QThEMkEucG5n](https://user-images.githubusercontent.com/47653238/145839588-0f9477af-a52c-42b1-962a-3eb4144bfa01.png) ![92e6b656f7a5312da10c651053dba7b55e3d1669efb65a44a522f44c65a5da56QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQwODkwMDI2NF9BNDM3MzM1Qy1DN0JGLTQxNTEtQjc0Mi0wNTJCQzY5QUZBQjQucG5n](https://user-images.githubusercontent.com/47653238/145839601-6ad0ec60-6ad6-4097-8c3d-e75331e261f4.png)
> 
> ![fe42cec8c663a63acc5403cabb0e4c47ce6f3935c3a7ef7498d425a96715df72QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQwODY2NzY2NF8xNkE0Nzc0Qi1ERkQ1LTQ4Y2UtQjM4Ny0wMUMyMTI5QUZBNzEucG5n](https://user-images.githubusercontent.com/47653238/145839614-7063359b-280c-4317-9a55-ce39d7a930a5.png)
> 
> 获取参数好像出错了

add方法，返回值获取到，但是参数获取不到
