### ISSUE TITLE
面板刷新无法读取数据

### ISSUE THREAD

**Issue by HwwwwwLemon** [liuzhihang/doc-view#38]
**Bug 描述**
简要描述 Bug 信息

1. 面板刷新无法读取数据
2. List、JSONObject，Map等参数还是不显示，没报错。

**Version**
 - Doc View: v1.2.2
 - IDEA 2021.2.2

**Bug 详情**
异常日志、可能导致的原因、参数信息等

![549f2308370a9821d5ee809c87048657672a9797c40d0b0f0d8070cf880a8ddaQzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQ2Nzg0ODkyMV8zQzU3NTNDMC1BMjA4LTQzYjUtQUU0RC0wNDIwQjQ5M0IwMEEucG5n](https://user-images.githubusercontent.com/47653238/145954873-a23084bf-466c-4d9f-8f0c-e3b1cb7ff4a6.png)

**Comment by liuzhihang** [comment]
这个功能没有开发完毕，你需要先点旁边的过滤， 选择要指定的范围

**Comment by liuzhihang** [comment]
List  这些都是 get 请求的参数么？ 具体是什么样子的

**Comment by HwwwwwLemon** [comment]
![81b438672f8387f70b93111e61a59fafcc7834e9c33c7e4fe2fca7ee545b5b9cQzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQ3NzM2NTYyMV81NUE1NEJBOC0zOUU0LTRlN2QtODIxOS1DOTc2NjA1OURCQjEucG5n](https://user-images.githubusercontent.com/47653238/145980112-fcb8f4c6-5df1-4b25-9d52-ec38a5a40984.png)
![d0e94182d44fd67387fbc0de26bb5ba3090769beef171d6e73452ca5b0393739QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQ3NzQ4Njg0M18xRDg0MDk5My0xRUNELTRkYTctQTZGMy1DNzgzMkJGREU3RTYucG5n](https://user-images.githubusercontent.com/47653238/145980433-103057d2-c45b-4b2f-98c5-af8c11c3375d.png)

![b9d972f1f8f65891c1d59b64f31eb1d29a5f6992708df0c907da15d9f9b47aa1QzpcVXNlcnNcSHd3d3d3XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxOTEwNzA1MjgzX3YyXEltYWdlRmlsZXNcMTYzOTQ3NzQzNzYxMV9FQkY1RDBCRS1BMDUwLTQ4MDUtQjM2My01NDRCRTM5MUUxQTQucG5n](https://user-images.githubusercontent.com/47653238/145980286-cdb0930f-531e-4c4b-a2d3-da170607878c.png)

比如这些参数都不会显示，有些Map的返回值也不显示

**Comment by liuzhihang** [comment]
是的，这个参数我不能解析出来具体内容是什么，全部都不会展示的。 Map 就是 KV，具体我不知道 Key 是什么，所以无法展示的。

**Comment by HwwwwwLemon** [comment]
> 是的，这个参数我不能解析出来具体内容是什么，全部都不会展示的。 Map 就是 KV，具体我不知道 Key 是什么，所以无法展示的。

👌🏻，明白

**Comment by liuzhihang** [comment]
@HwwwwwLemon  已经可以了。 刚收到邮件，通过审核了。 现在不需要先选择过滤，就可以刷新。

**Comment by HwwwwwLemon** [comment]
> @HwwwwwLemon  已经可以了。 刚收到邮件，通过审核了。 现在不需要先选择过滤，就可以刷新。

好的，我去更新一下。
1.2.2我下载本地安装来着。
还有个问题，就是首次生成注释后再次编辑会NPE，方法名也会变成中文，注释里的参数会丢失，要不要重新开个issue？
最后，直推yapi简直不要太爽
