### ISSUE TITLE
idea的插件市场搜索不到 然后本地安装显示Plugin 'Doc View' is incompatible with this installation

### ISSUE THREAD

**Issue by RagdollNoone** [liuzhihang/doc-view#43]
**Bug 描述**
简要描述 Bug 信息

**Version**
 - Doc View: [e.g. v1.2.3]
 - IDEA [e.g. 2019.3]

**Bug 详情**
异常日志、可能导致的原因、参数信息等
![idea](https://user-images.githubusercontent.com/38310859/156691806-b07a4dbb-e8b7-4540-9c12-cfde5b730a94.png)
![error](https://user-images.githubusercontent.com/38310859/156691818-270daa17-7190-4236-ad93-1dae48fa310f.png)
![market](https://user-images.githubusercontent.com/38310859/156691905-da08fa0d-2c66-41c1-be73-b5d17dedadcb.png)

**Comment by liuzhihang** [comment]
这种是你的 IDEA 版本太低了
