### ISSUE TITLE
能否支持识别自定义注解内容

### ISSUE THREAD

**Issue by 1044070878** [liuzhihang/doc-view#47]
**希望增加什么功能**
期望增加支持识别自定义注解内容

**该功能的使用场景**
原有项目使用类似swagger的一套注解，目前无法识别到相关注释信息.

**建议或实现方式**
通过配置的形式增加

**Comment by liuzhihang** [comment]
能补充注解都有什么信息么？ 给一个样例最好，我稍微想一下。
