### ISSUE TITLE
社区idea 点击controller的文档图标出现报错

### ISSUE THREAD

**Issue by junziqiao** [liuzhihang/doc-view#48]
**Bug 描述**
社区idea 点击controller的文档图标出现报错，

**Version**
 - Doc View: [ v1.2.4]
 - IDEA [ 2022.1]

**Bug 详情**
异常日志、可能导致的原因、参数信息等
<img width="999" alt="image" src="https://user-images.githubusercontent.com/41858086/163585912-9773eca5-9d5a-44e4-9db2-4437ea46bf2b.png">

**Comment by liuzhihang** [comment]
方便发一下参数么？ 或者是不是有重载之类的

**Comment by junziqiao** [comment]
我更新一下版本好了
