### ISSUE TITLE
一定要配置YApi？

### ISSUE THREAD

**Issue by ayang0422** [liuzhihang/doc-view#51]
**Bug 描述**
不配置Yapi不能上传到其他平台

**Version**
 - Doc View: [v1.2.6]
 - IDEA [2021.1]

**Bug 详情**

**Comment by ayang0422** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/43911138/167234375-beb6e9da-120a-47c6-821d-22e79c9999f3.png">
针对upload All按钮

**Comment by liuzhihang** [comment]
可以不配置啊，现在出现必须配置的情况了么？我检查一下

**Comment by ayang0422** [comment]
> 可以不配置啊，现在出现必须配置的情况了么？我检查一下

这个upload All按钮现在只能上传YApi了，我刚刚改了一下跟右边的upload 按钮改成一样的了

**Comment by liuzhihang** [comment]
好的，我已经看到这块了，因为代码被覆盖的原因导致的

**Comment by ayang0422** [comment]
怎么能联系到作者啊，对这个还有点想法，希望能聊聊啊

**Comment by liuzhihang** [comment]
可以加我微信 liuzhihangcom
