### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by qiub649691422** [liuzhihang/doc-view#56]
**希望增加什么功能**
 
Bean中有list泛型属性， 导出的请求返回参数 不想展示element， 能不能添加个checkbox控制该行为

不想展示element
![image](https://user-images.githubusercontent.com/23074909/175815909-6024584b-4539-43fb-b42e-be6808668967.png)

希望表格中的类型，与json对应，不展示element

**Comment by liuzhihang** [comment]
@zh-d-d  包括 Map 的也一块看一下，这个可以考虑直接移除掉 element，不用做 checkbox 控制

**Comment by zh-d-d** [comment]
> @zh-d-d 包括 Map 的也一块看一下，这个可以考虑直接移除掉 element，不用做 checkbox 控制

已经在处理。详情修改内容可以[点击](https://github.com/liuzhihang/doc-view/pull/58/commits/b03c7dc58c0bef251c9868995124151a6bdfbef1)查看。
