### ISSUE TITLE
yapi上传服务端报错

### ISSUE THREAD

**Issue by qiub649691422** [liuzhihang/doc-view#57]
**Bug 描述**
简要描述 Bug 信息
安装api-generator插件可以上传
**Version**
 - Doc View: [e.g. v1.0.0]
 - IDEA [e.g. 2021.1]

**Bug 详情**
异常日志、可能导致的原因、参数信息等

**Comment by zh-d-d** [comment]
可能是.idea文件夹下的生成的配置信息有问题

**Comment by liuzhihang** [comment]
@zh-d-d  近期较忙，帮忙看一下。

**Comment by zh-d-d** [comment]
> @zh-d-d 近期较忙，帮忙看一下。

已经在处理。详情修改内容可以[点击](https://github.com/liuzhihang/doc-view/pull/58/commits/852232b6510fe70d1ce1ea13d8d3c2b54444dccf)查看。
