### ISSUE TITLE
是否能支持社区版idea的http client请求呢

### ISSUE THREAD

**Issue by dbin1573** [liuzhihang/doc-view#60]
是否能支持社区版idea的http client请求呢

**Comment by liuzhihang** [comment]
http client 是 IDEA UI 版本提供的功能。我这里只能生成相关 http client 的请求。  你可以考虑使用 VS Code 的 Rest Client 发送 HTTP 请求。
https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
https://marketplace.visualstudio.com/items?itemName=humao.rest-client

---

如果你说的不是基于 IDEA UI 的 Http Client，而是图形化自己设计的，类似 postman 这种 UI。我暂时是没有这个打算。不过有一个小兄弟正在开发这块，需要等他提 PR 之后，合并进来就会支持这个功能了。具体时间我也不知道。
