### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by isliudong** [liuzhihang/doc-view#70]
导出空指针了

**Version**
 - Doc View: [1.3.0]
 - IDEA [2022.1]

**Bug 详情**
![image](https://user-images.githubusercontent.com/53169912/187160136-01450f07-48a5-4008-8299-1efb16dd2d6e.png)

**Comment by liuzhihang** [comment]
这是导出什么样的接口时出现的问题

**Comment by isliudong** [comment]
> 这是导出什么样的接口时出现的问题

![image](https://user-images.githubusercontent.com/53169912/187369163-48860c84-d1b5-4f29-a35f-8768e78f0ecb.png)
我导出接口文档似乎都会报错

**Comment by liuzhihang** [comment]
是从目录树导出时候报错么？你点预览，在预览界面导出呢？就是行号旁边的图标预览。目录树这个我一会看一下。

**Comment by isliudong** [comment]
预览导出是好使的

**Comment by liuzhihang** [comment]
好，我排查一下，目录树功能还有很多需要完善。
