### ISSUE TITLE
自定义标题不显示

### ISSUE THREAD

**Issue by tmlaes** [liuzhihang/doc-view#71]
**Bug 描述**
修改markdown template 自定义标题时，doc views时时空白的

![image](https://user-images.githubusercontent.com/16698843/187648165-f2d5b918-93f9-4c2a-a8cb-cffa7936be8c.png)
![image](https://user-images.githubusercontent.com/16698843/187648722-05d14dae-8eef-442d-bfe4-aa6e7e187c59.png)

**Comment by liuzhihang** [comment]
我验证了，确实存在这个问题，我排查一下

**Comment by Superman-lion** [comment]
> 

thank you!

**Comment by liuzhihang** [comment]
你可以试着写 #[[##]]#   #[[###]]#。这种写法，在中括号内部写标题。 我查了一下这种情况是因为 Velocity 的原因，后续我会排查一下。

**Comment by liuzhihang** [comment]
https://stackoverflow.com/questions/39526205/double-hash-in-template

**Comment by Superman-lion** [comment]
> https://stackoverflow.com/questions/39526205/double-hash-in-template



> 你可以试着写 #[[##]]# #[[###]]#。这种写法，在中括号内部写标题。 我查了一下这种情况是因为 Velocity 的原因，后续我会排查一下。

好的，谢谢
