### ISSUE TITLE
升级1.3.8版本后，右击鼠标无法编辑实体类

### ISSUE THREAD

**Issue by lhaixiong** [liuzhihang/doc-view#83]
**Bug 描述**
简要描述 Bug 信息

**Version**
 - Doc View: [v1.3.8]
 - IDEA [2022.3.3]

**Bug 详情**
升级1.3.8版本后，右击鼠标无法编辑实体类
![11](https://github.com/liuzhihang/doc-view/assets/28646024/d2640bd5-f8a0-4a36-8eb3-8c198c46df99)

**Comment by lhaixiong** [comment]
之前1.3.0版本，右击鼠标是可以出现doceditor菜单并编辑实体类的
![image](https://github.com/liuzhihang/doc-view/assets/28646024/7e85b4fd-4b6e-485b-b421-d2ee973f2030)

**Comment by liuzhihang** [comment]
这个版本我还原回来
